#!/bin/bash
current_dr=$(pwd)/bin
echo "run the following command to add the ope to your path"
echo "export PATH=$current_dr:\$PATH"
echo " "
echo "congrats! you should have the ope command now"
echo "check by running the command ope, if a display of different commands comes up"
echo "if it does- you have the command"
echo " "
echo "to make a new project follow these instructions:"
echo "create a new repository, on github, outside of the terminal"
echo "copy the ssh url of your new repsository to clipboard"
echo "it should look similar to 'git@github.com:your-github-id/repo-name.git'"
echo "go to your root directory, making sure you're not in the tools directory"
echo "once you're in your root directory, create a textbook by running the new_project command"
echo "the command you run should look like this:"
echo "ope new_project <project_name> [repo_url]"
echo "this should populate your github repo"
echo " "
echo "once you have your project set up, you can make a new textbook within it"
echo "cd into the folder called books"
echo "use the ope new_project command, it should look like this: "
echo "ope new_book <book_name>"
echo " "
echo "if you have any questions or want more information of how to edit the content of your textbook"
echo "check out: https://www.youtube.com/watch?v=-_0HD_oAK5o" 
